services:
  - type: web
    name: tactology-department-api
    env: node
    buildCommand: npm install -g pnpm && pnpm install && pnpm rebuild bcrypt --build-from-source && pnpm run build
    startCommand: pnpm run start:prod